name: 'ServerFan Notifier'
description: 'Send notification or deploy command to server.fan service'
branding:
  icon: 'bell'
  color: 'blue'
inputs:
  token:
    description: 'ServerRun User Token'
    required: true
  status:
    description: 'Job status, auto use github.job.status'
    default: ${{ job.status }}
  success:
    description: 'Notification text if success'
    default: 'Action Success'
  failed:
    description: 'Error text if failed'
    default: 'Action Failed'
  command:
    description: 'Command to server.fan if you need'
  source:
    description: 'Notification source, default is your repo name'
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/hack-fan/skadi-action'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.status }}
    - ${{ inputs.success }}
    - ${{ inputs.failed }}
    - ${{ inputs.command }}
    - ${{ inputs.source }}
